[2024-06-28T10:31:07.617-0400] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T10:31:07.643-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:04:30+00:00 [queued]>
[2024-06-28T10:31:07.654-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:04:30+00:00 [queued]>
[2024-06-28T10:31:07.655-0400] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-28T10:31:07.703-0400] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_into_mysql> on 2024-06-27 00:04:30+00:00
[2024-06-28T10:31:07.717-0400] {standard_task_runner.py:63} INFO - Started process 234071 to run task
[2024-06-28T10:31:07.741-0400] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'api_cuevana3_movie', 'insert_into_mysql', 'scheduled__2024-06-27T00:04:30+00:00', '--job-id', '420', '--raw', '--subdir', 'DAGS_FOLDER/movie_recommend.py', '--cfg-path', '/tmp/tmp_d1dqbdp']
[2024-06-28T10:31:07.747-0400] {standard_task_runner.py:91} INFO - Job 420: Subtask insert_into_mysql
[2024-06-28T10:31:07.819-0400] {task_command.py:426} INFO - Running <TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:04:30+00:00 [running]> on host walter-VirtualBox
[2024-06-28T10:31:07.943-0400] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='api_cuevana3_movie' AIRFLOW_CTX_TASK_ID='insert_into_mysql' AIRFLOW_CTX_EXECUTION_DATE='2024-06-27T00:04:30+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-27T00:04:30+00:00'
[2024-06-28T10:31:07.944-0400] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T10:31:08.056-0400] {logging_mixin.py:188} INFO - Error al insertar en MySQL: 1406 (22001): Data too long for column 'descriptions' at row 1
[2024-06-28T10:31:08.058-0400] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T10:31:08.060-0400] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T10:31:08.066-0400] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=api_cuevana3_movie, task_id=insert_into_mysql, run_id=scheduled__2024-06-27T00:04:30+00:00, execution_date=20240627T000430, start_date=20240628T143107, end_date=20240628T143108
[2024-06-28T10:31:08.170-0400] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T10:31:08.199-0400] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T10:31:08.202-0400] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T11:08:41.854-0400] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T11:08:41.881-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:04:30+00:00 [queued]>
[2024-06-28T11:08:41.887-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:04:30+00:00 [queued]>
[2024-06-28T11:08:41.887-0400] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-28T11:08:41.928-0400] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_into_mysql> on 2024-06-27 00:04:30+00:00
[2024-06-28T11:08:41.936-0400] {standard_task_runner.py:63} INFO - Started process 239575 to run task
[2024-06-28T11:08:41.939-0400] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'api_cuevana3_movie', 'insert_into_mysql', 'scheduled__2024-06-27T00:04:30+00:00', '--job-id', '500', '--raw', '--subdir', 'DAGS_FOLDER/movie_recommend.py', '--cfg-path', '/tmp/tmpv0f6jcsw']
[2024-06-28T11:08:41.942-0400] {standard_task_runner.py:91} INFO - Job 500: Subtask insert_into_mysql
[2024-06-28T11:08:42.032-0400] {task_command.py:426} INFO - Running <TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:04:30+00:00 [running]> on host walter-VirtualBox
[2024-06-28T11:08:42.174-0400] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='api_cuevana3_movie' AIRFLOW_CTX_TASK_ID='insert_into_mysql' AIRFLOW_CTX_EXECUTION_DATE='2024-06-27T00:04:30+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-27T00:04:30+00:00'
[2024-06-28T11:08:42.177-0400] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T11:08:42.273-0400] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T11:08:42.276-0400] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T11:08:42.281-0400] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=api_cuevana3_movie, task_id=insert_into_mysql, run_id=scheduled__2024-06-27T00:04:30+00:00, execution_date=20240627T000430, start_date=20240628T150841, end_date=20240628T150842
[2024-06-28T11:08:42.328-0400] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T11:08:42.355-0400] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T11:08:42.357-0400] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T11:24:56.892-0400] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T11:24:56.914-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:04:30+00:00 [queued]>
[2024-06-28T11:24:56.924-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:04:30+00:00 [queued]>
[2024-06-28T11:24:56.925-0400] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-28T11:24:56.957-0400] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_into_mysql> on 2024-06-27 00:04:30+00:00
[2024-06-28T11:24:56.971-0400] {standard_task_runner.py:63} INFO - Started process 243414 to run task
[2024-06-28T11:24:56.978-0400] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'api_cuevana3_movie', 'insert_into_mysql', 'scheduled__2024-06-27T00:04:30+00:00', '--job-id', '550', '--raw', '--subdir', 'DAGS_FOLDER/movie_recommend.py', '--cfg-path', '/tmp/tmpdpm0do4s']
[2024-06-28T11:24:56.989-0400] {standard_task_runner.py:91} INFO - Job 550: Subtask insert_into_mysql
[2024-06-28T11:24:57.161-0400] {task_command.py:426} INFO - Running <TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:04:30+00:00 [running]> on host walter-VirtualBox
[2024-06-28T11:24:57.341-0400] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='api_cuevana3_movie' AIRFLOW_CTX_TASK_ID='insert_into_mysql' AIRFLOW_CTX_EXECUTION_DATE='2024-06-27T00:04:30+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-27T00:04:30+00:00'
[2024-06-28T11:24:57.350-0400] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T11:24:57.516-0400] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T11:24:57.517-0400] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/airflow/dags/movie_recommend.py", line 115, in insert_into_mysql
    title = movie['title']
            ~~~~~^^^^^^^^^
TypeError: string indices must be integers, not 'str'
[2024-06-28T11:24:57.525-0400] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=api_cuevana3_movie, task_id=insert_into_mysql, run_id=scheduled__2024-06-27T00:04:30+00:00, execution_date=20240627T000430, start_date=20240628T152456, end_date=20240628T152457
[2024-06-28T11:24:57.560-0400] {standard_task_runner.py:110} ERROR - Failed to execute job 550 for task insert_into_mysql (string indices must be integers, not 'str'; 243414)
[2024-06-28T11:24:57.617-0400] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-28T11:24:57.658-0400] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T11:24:57.665-0400] {local_task_job_runner.py:222} INFO - ::endgroup::
