[2024-06-28T09:53:29.380-0400] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T09:53:29.465-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:01:30+00:00 [queued]>
[2024-06-28T09:53:29.485-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:01:30+00:00 [queued]>
[2024-06-28T09:53:29.485-0400] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-28T09:53:29.563-0400] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_into_mysql> on 2024-06-27 00:01:30+00:00
[2024-06-28T09:53:29.574-0400] {standard_task_runner.py:63} INFO - Started process 230671 to run task
[2024-06-28T09:53:29.580-0400] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'api_cuevana3_movie', 'insert_into_mysql', 'scheduled__2024-06-27T00:01:30+00:00', '--job-id', '400', '--raw', '--subdir', 'DAGS_FOLDER/movie_recommend.py', '--cfg-path', '/tmp/tmptssdueju']
[2024-06-28T09:53:29.586-0400] {standard_task_runner.py:91} INFO - Job 400: Subtask insert_into_mysql
[2024-06-28T09:53:29.674-0400] {task_command.py:426} INFO - Running <TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:01:30+00:00 [running]> on host walter-VirtualBox
[2024-06-28T09:53:29.783-0400] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='api_cuevana3_movie' AIRFLOW_CTX_TASK_ID='insert_into_mysql' AIRFLOW_CTX_EXECUTION_DATE='2024-06-27T00:01:30+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-27T00:01:30+00:00'
[2024-06-28T09:53:29.784-0400] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T09:53:29.900-0400] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T09:53:29.901-0400] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/airflow/dags/movie_recommend.py", line 133, in insert_into_mysql
    cursor.execute(insert_query,(title,years,quality,duration,rating,descriptions,genre,
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py", line 359, in execute
    prepared = self._cnx.prepare_for_mysql(params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 866, in prepare_for_mysql
    result = self._cmysql.convert_to_mysql(*params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_mysql_connector.MySQLInterfaceError: Python type list cannot be converted
[2024-06-28T09:53:29.908-0400] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=api_cuevana3_movie, task_id=insert_into_mysql, run_id=scheduled__2024-06-27T00:01:30+00:00, execution_date=20240627T000130, start_date=20240628T135329, end_date=20240628T135329
[2024-06-28T09:53:29.955-0400] {standard_task_runner.py:110} ERROR - Failed to execute job 400 for task insert_into_mysql (Python type list cannot be converted; 230671)
[2024-06-28T09:53:29.992-0400] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-28T09:53:30.019-0400] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T09:53:30.020-0400] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T11:03:03.354-0400] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T11:03:03.391-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:01:30+00:00 [queued]>
[2024-06-28T11:03:03.413-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:01:30+00:00 [queued]>
[2024-06-28T11:03:03.415-0400] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-28T11:03:03.450-0400] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_into_mysql> on 2024-06-27 00:01:30+00:00
[2024-06-28T11:03:03.457-0400] {standard_task_runner.py:63} INFO - Started process 237375 to run task
[2024-06-28T11:03:03.460-0400] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'api_cuevana3_movie', 'insert_into_mysql', 'scheduled__2024-06-27T00:01:30+00:00', '--job-id', '460', '--raw', '--subdir', 'DAGS_FOLDER/movie_recommend.py', '--cfg-path', '/tmp/tmphwz9gbwo']
[2024-06-28T11:03:03.461-0400] {standard_task_runner.py:91} INFO - Job 460: Subtask insert_into_mysql
[2024-06-28T11:03:03.520-0400] {task_command.py:426} INFO - Running <TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:01:30+00:00 [running]> on host walter-VirtualBox
[2024-06-28T11:03:03.674-0400] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='api_cuevana3_movie' AIRFLOW_CTX_TASK_ID='insert_into_mysql' AIRFLOW_CTX_EXECUTION_DATE='2024-06-27T00:01:30+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-27T00:01:30+00:00'
[2024-06-28T11:03:03.676-0400] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T11:03:03.794-0400] {logging_mixin.py:188} INFO - Error al insertar en MySQL: 1146 (42S02): Table 'cuevana3.movies' doesn't exist
[2024-06-28T11:03:03.798-0400] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T11:03:03.799-0400] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T11:03:03.803-0400] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=api_cuevana3_movie, task_id=insert_into_mysql, run_id=scheduled__2024-06-27T00:01:30+00:00, execution_date=20240627T000130, start_date=20240628T150303, end_date=20240628T150303
[2024-06-28T11:03:03.871-0400] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T11:03:03.894-0400] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T11:03:03.895-0400] {local_task_job_runner.py:222} INFO - ::endgroup::
